### ISSUE TITLE
Need review pull request to fix branch run.

### ISSUE THREAD

**Issue by blcc** [NorESMhub/CTSM#10]
Hi,
I am preparing the release of NorCPM, which is a set of scripts to do data assimilation with NorESM.
NorCPM use branch as RUN_TYPE to do simulation. In CTSM, branch is not allowed but it should be.
The bug was submitted at CLM at ESCOMP and fixed with tiny modification. Please see following issue:
 https://github.com/ESCOMP/ctsm/issues/786
The pull request of this fix is submitted. Please review and merge it to master branch.

**Comment by huitang-earth** [comment]
@blcc The changes are not supposed to go to the master branch in CTSM repo. Please find the appropriate branch for your changes.

**Comment by MichaelSchulzMETNO** [comment]
The master is not yet uptodate with ESCOMP. The branch for NorESM2 is this one: release-clm5.0.14-Nor. Would this be the one to merge you change into?

**Comment by blcc** [comment]
@huitang-earth @MichaelSchulzMETNO 
Thanks you very much. My PR is wrong at branch. I'll create another one to release-clm5.0.14-Nor.
