### ISSUE TITLE
Update CTSM with upstream

### ISSUE THREAD

**Issue by ka7eh** [NorESMhub/CTSM#23]
@kjetilaas @DirkOlivie @MichaelSchulzMETNO is there any info on the process of updating ctsm? Any instructions, roadmap, concerns, copyright stuff, etc.?

There are some scripts in NCAR's version that I'd like to use in FATES Platform (specifically subset_data), and I rather have it directly here than copy/pasting code to make sure the copyright stuff are respected, and noresm gets attribution too.

Looking at the commits, looks like the code has not changed significantly from ESCOMP version, and as far as I can tell, the initial commits made by noresm are merged into the upstream.
Still, if I merge ESCOMP master into clm-Nor-dev, I get lots of merge conflicts.
If there's no actual noresm-specific code here, maybe we can accept all the incoming changes from ESCOMP?

@yelizy @evalieungh @lasseke FYI

**Comment by kjetilaas** [comment]
Hi @ka7eh! Did you check out the[ README.md](https://github.com/NorESMhub/CTSM/blob/clm-Nor-dev/README.md)? It describes the different branches of this repo, where master is intended to follow escomp without noresm specific changes. Fell free to update this whenever you like. 

If you need other branches, we could potentially add that, but the idea is that the Nor branches should include the NorESM specific updates, and can potentially diverge somewhat from the escomp code.

**Comment by ka7eh** [comment]
No, I hadn't seen the README! :) Thanks for sharing.
Now I see the master branch. It was hiding among stale branches. I'll give it a try and update it.

**Comment by ka7eh** [comment]
I created a PR, but it needs two approvals.
Alternatively, if someone with admin access can remove the protection from the branch, I'll merge it myself. I don't think protection is need on master. If something goes wrong, we can always remove it and push the latest stuff directly from ESCOMP.
