### ISSUE TITLE
Define and carry out CTSM/Fates F and B compset simulations with NorESM3alpha

### ISSUE THREAD

**Issue by mvertens** [NorESMhub/CTSM#34]
### NOTE: Be sure to read the relevant documentation and user forums

We have limited staff and ability to provide support. Here are some resources that might provide help:
- User's Guide: https://escomp.github.io/ctsm-docs/doc/build/html/users_guide/index.html
- CLM Forum: https://bb.cgd.ucar.edu/forums/land-modeling-clm
- README files amongst the source code
- GitHub CTSM issues: https://github.com/escomp/ctsm/issues/
- Also make sure this issue is unique to CTSM and not really an issue with CESM or CIME

### Details of support request

[Fill in details here.]

### Important details of your setup / configuration so we can better assist you

**CTSM version you are using:** [output of `git describe`]

**Have you made any modifications to code, xml files, etc.?** [Yes / No]

[If Yes: Please point us to your modifications. However: In general we can NOT support problems with modified code. Try to show the problem without modifications.]

**If you are having problems with a specific case: Is your case on a machine accessible to most CTSM developers (e.g., an NCAR machine)?** [Yes / No]

If Yes:

- Location of case directory: [Fill this in]

- Location of run directory: [Fill this in]

[If No: Please make sure you have included all important input and output needed to understand your issue, either by pasting it into the issue text, or by attaching relevant files. However: We are less likely to be able to reproduce your problem if the issue is NOT on an NCAR machine.]

**Comment by mvdebolskiy** [comment]
@mvertens  NorESMhub/CTSM branch with two-stream turned on: `feature/fates-twostream-param`.
