### ISSUE TITLE
Performance test of NorESM with FATES

### ISSUE THREAD

**Issue by kjetilaas** [NorESMhub/CTSM#39]
Initial performance test of NorESM with FATES. This will give a baseline, against which further performance improvements can be compared. 

- [x] Update NorESMhub/CTSM (Mat)
- [ ] Define compset, resolution and simulation length (Rosie)
- [ ] Run test (Mariana)

**Comment by mvdebolskiy** [comment]
`noresm` branch with the latest tag: [ctsm5.1.dev151-noresm_v1](https://github.com/NorESMhub/CTSM/releases/tag/ctsm5.1.dev151-noresm_v1) has been updated.
