### ISSUE TITLE
Post process/visualize SE output

### ISSUE THREAD

**Issue by kjetilaas** [NorESMhub/CTSM#43]
If NorESM2.5 and NorESM3 will use Spectral Element grid, we need a strategy for post processing and visualizing the CLM(-FATES) output. This might already be in place somewhere, but posting it here for now...

**Comment by gold2718** [comment]
I would like to add this to the NorESM project so that we keep CLM needs in mind as we work on integrating CAM-SE (assuming we decide on using SE).
In the short term, we are developing a testing program to help with the decision and that will of course involve some post-processing.
