### ISSUE TITLE
Initial conditions and tuning for I compsets

### ISSUE THREAD

**Issue by mvdebolskiy** [NorESMhub/CTSM#75]
Since  we wil be using trigrid and FATES, NCAR's inintial conditionsfiles might not work our release version, due to initial interpolation putting coldstart values in some of the cells. 
Parameter files should also be updated since fates will give a different land state compared to clm60 in bgc mode.

**Comment by kjetilaas** [comment]
I am closing this issue, and opening a separate for the creating initial conditions for . We no longer plan to use trigrid and the parameter tuning will be covered in separate issues/efforts.
